services:
  _defaults:
    autowire: true
    autoconfigure: true
  Pixel\NewsBundle\Controller\Website\:
    resource: '../../Controller/Website'

  Pixel\NewsBundle\Twig\SettingsExtension:
    public: false
    autowire: true
    tags:
      - {name: twig.extension}

  Pixel\NewsBundle\Twig\NewsExtension:
    public: false
    autowire: true
    tags:
      - {name: twig.extension}